--- 
    services: |-
        -docker
        before_install - docker build -t rogerloh/react-docker -f Dockerfile.dev .
        script - docker run rogerloh/react-docker npm run test -- --coverage
    sudo: required
    
